### PR TITLE
fix build with php 8.6

### PR DESCRIPTION
**Pull request by pavetheway91**
https://github.com/php/php-src/commit/0471420514c1500c2127e357e3c352602af7f076

### CODE REVIEW

File: libdeflate.c [hunk 1]
```diff
@@ -103,12 +103,19 @@ static inline zend_string* php_libdeflate_compress(zend_string *data, zend_long
 	return result;
 }
 
+// php7 warns rather that throws with ZEND_PARSE_PARAMETERS_START
+#if PHP_VERSION_ID >= 80000
+#define LIBDEEFLATE_PARSE_PARAMS() ZEND_PARSE_PARAMETERS_START(1, 2)
+#else
+#define LIBDEEFLATE_PARSE_PARAMS() ZEND_PARSE_PARAMETERS_START_EX(ZEND_PARSE_PARAMS_THROW, 1, 2)
+#endif
```
Comment (dktapps) [inline libdeflate.c:111]: The macro seems a bit unnecessary since it's only used in 1 place, an inline if/else would suffice

**Review by dktapps — DISMISSED** [review]
Looks mostly fine, thanks for the PR! Just one or two minor nits

File: libdeflate.c (hunk 1 above)
Comment (pavetheway91) [reply libdeflate.c:111]: LLVM doesn't like if I do that

```
/mnt/libdeflate.c:111:2: error: '#' is not followed by a macro parameter
  111 | #if PHP_VERSION_ID >= 80000
      |  ^
/mnt/libdeflate.c:112:2: error: expected identifier or '('
  112 |         ZEND_PARSE_PARAMETERS_START(1, 2) \
      |         ^
/usr/local/include/php/Zend/zend_API.h:1506:2: note: expanded from macro 'ZEND_PARSE_PARAMETERS_START'
 1506 |         ZEND_PARSE_PARAMETERS_START_EX(0, min_num_args, max_num_args)
      |         ^
/usr/local/include/php/Zend/zend_API.h:1474:75: note: expanded from macro 'ZEND_PARSE_PARAMETERS_START_EX'
 1474 | #define ZEND_PARSE_PARAMETERS_START_EX(flags, min_num_args, max_num_args) do { \
      |                                                                           ^
2 errors generated.
```

Comment (pavetheway91) [reply libdeflate.c:111]: This goes a bit beyond just a build fix, but replacing that PHP_LIBDEFLATE_FUNC macro with something like this could work.

```
static void php_libdeflate_func(
	INTERNAL_FUNCTION_PARAMETERS,
	php_libdeflate_compress_bound_func compressBoundFunc,
	php_libdeflate_compress_func compressFunc
) {
	zend_string *data;
	zend_long level = 6;

#if PHP_VERSION_ID >= 80000
	ZEND_PARSE_PARAMETERS_START(1, 2)
#else
	ZEND_PARSE_PARAMETERS_START_EX(ZEND_PARSE_PARAMS_THROW, 1, 2)
#endif
		Z_PARAM_STR(data)
		Z_PARAM_OPTIONAL
		Z_PARAM_LONG(level)
	ZEND_PARSE_PARAMETERS_END();

	zend_string *result = php_libdeflate_compress(data, level, compressBoundFunc, compressFunc);
	if (result == NULL) {
		return;
	}
	RETURN_STR(result);
}

PHP_FUNCTION(libdeflate_deflate_compress)
{
	php_libdeflate_func(INTERNAL_FUNCTION_PARAM_PASSTHRU, libdeflate_deflate_compress_bound, libdeflate_deflate_compress);
}

PHP_FUNCTION(libdeflate_zlib_compress)
{
	php_libdeflate_func(INTERNAL_FUNCTION_PARAM_PASSTHRU, libdeflate_zlib_compress_bound, libdeflate_zlib_compress);
}

PHP_FUNCTION(libdeflate_gzip_compress)
{
	php_libdeflate_func(INTERNAL_FUNCTION_PARAM_PASSTHRU, libdeflate_gzip_compress_bound, libdeflate_gzip_compress);
}
```

Comment (dktapps) [reply libdeflate.c:111]: I see the issue, you'd probably have to wrap the whole ZPP macro from START to END in if/else. Not worth the hassle in that case, the macro is fine
